"""``!pack.txt`` parsing, routing and per-group flags — utils.exe parity.

Ground truth for everything asserted here:

* the two real config files of the ``OCT_get_started`` corpus,
  ``art/!pack.txt`` (hand-tuned, 46 palette blocks) and ``art/!pack_pal.txt``
  (generated by ``art/pack_palettes.py``, which documents the same grammar in
  prose) — quoted verbatim in the fixtures below;
* the tag vocabulary read out of the reference ``utils.exe``
  (``<FULLSIZE> <BG> <ADD> <BUMP> <REFL> <DUDV> <ALPHA> <OPAQUE>``) and the
  flag bit each one sets, measured by packing a probe sprite per tag and
  reading octBmp_t offset 44 back;
* the ALPHA auto-detection thresholds, pinned by binary-searching the same
  ``utils.exe`` with synthetic sprites (see :mod:`config`).

The corpus itself is read-only and gitignored, so the numbers are pinned here
rather than read at test time.
"""
from __future__ import annotations

import numpy as np
import pytest
from PIL import Image

from config import (
    PACK_TXT_ALPHA_ENABLE_RATIO,
    PACK_TXT_ALPHA_TAGGED_RATIO,
    PACK_TXT_OPAQUE_MIN_ALPHA,
    PACK_TXT_TRANSPARENT_MAX_ALPHA,
    SpriteFlag,
)
from packtxt import (
    PackTxtError,
    find_pack_txt,
    group_alpha_enabled,
    parse_pack_txt,
    parse_pack_txt_text,
    resolve_sprite_flags,
    sprite_alpha_counts,
)

# ─────────────────────────────────────────────────────────────────────────────
# Fixtures transcribed from the corpus
# ─────────────────────────────────────────────────────────────────────────────

# The first, last and most interesting blocks of OCT_get_started/art/!pack.txt,
# CRLF line endings included (the real file has them).
CORPUS_PACK_TXT = "\r\n".join([
    "exported",
    "",
    "256",
    "*",
    "",
    "16",
    "cubetext_xl_*",
    "",
    "256",
    "<ALPHA><FULLSIZE>",
    "selectcube_*",
    "",
    "256",
    "<ALPHA><FULLSIZE>",
    "selectcube_orange_*",
    "",
    "16",
    "selectcube_transit_*",
    "",
    "4",
    "eyes_idle*",
    "eyesappear_*",
    "eyesblink_*",
    "eyeshappy_*",
    "",
    "129",
    "t_halftwist*",
    "",
    "64",
    "<FULLSIZE>",
    "ahover*",
    "",
    "64",
    "<FULLSIZE>",
    "ico*",
    "",
    "16",
    "qr_code*",
    "",
])

# A block of the generated OCT_get_started/art/!pack_pal.txt: a 4-colour font
# bucket, and a block whose second line is the bare sprite name "0" (the
# reserved placeholder) — proof that only blank lines delimit blocks.
CORPUS_PACK_PAL_TXT = "\n".join([
    "exported",
    "",
    "256",
    "<FULLSIZE>",
    "*",
    "",
    "4",
    "<FULLSIZE>",
    "font*",
    "",
    "32",
    "0",
    "dot",
    "carr*",
    "rabb*",
    "eyes_*",
    "",
])


# ─────────────────────────────────────────────────────────────────────────────
# Parsing
# ─────────────────────────────────────────────────────────────────────────────

def test_parses_the_corpus_blocks():
    cfg = parse_pack_txt_text(CORPUS_PACK_TXT)
    assert cfg.exported_dir == 'exported'
    assert len(cfg.buckets) == 10
    assert [b.max_colors for b in cfg.buckets] == \
        [256, 16, 256, 256, 16, 4, 129, 64, 64, 16]
    assert [b.index for b in cfg.buckets] == list(range(10))


def test_catch_all_bucket_is_first_and_matches_everything():
    cfg = parse_pack_txt_text(CORPUS_PACK_TXT)
    catch_all = cfg.buckets[0]
    assert catch_all.patterns == ('*',)
    assert catch_all.max_colors == 256
    assert catch_all.tags == ()
    # the reserved 0.png placeholder matches nothing else
    assert cfg.bucket_for('0') is catch_all
    assert cfg.assign('0') == (0, 256, 0)


def test_multiple_globs_share_one_bucket():
    cfg = parse_pack_txt_text(CORPUS_PACK_TXT)
    eyes = cfg.buckets[5]
    assert eyes.max_colors == 4
    assert eyes.patterns == ('eyes_idle*', 'eyesappear_*',
                             'eyesblink_*', 'eyeshappy_*')
    for name in ('eyes_idle_00', 'eyesappear_07', 'eyesblink_03', 'eyeshappy_1'):
        assert cfg.bucket_for(name) is eyes


def test_later_more_specific_mask_wins():
    """selectcube_transit_00 matches both selectcube_* and its own block."""
    cfg = parse_pack_txt_text(CORPUS_PACK_TXT)
    assert cfg.assign('selectcube_00') == (
        2, 256, int(SpriteFlag.ALPHA | SpriteFlag.FULLSIZE))
    assert cfg.assign('selectcube_orange_00') == (
        3, 256, int(SpriteFlag.ALPHA | SpriteFlag.FULLSIZE))
    # ... but the later 16-colour block takes the transit frames back, and
    # with them the FULLSIZE tag
    assert cfg.assign('selectcube_transit_00') == (4, 16, 0)


def test_fullsize_tag_sets_the_flag():
    cfg = parse_pack_txt_text(CORPUS_PACK_TXT)
    for name in ('ahover_00', 'ico_get_started'):
        group, colors, flags = cfg.assign(name)
        assert colors == 64
        assert flags == int(SpriteFlag.FULLSIZE)
        assert not flags & int(SpriteFlag.ALPHA)


def test_a_sprite_matching_nothing_falls_out_of_every_bucket():
    """utils.exe prints 'Unmatched palette %s, skipped'. Without a catch-all
    block there is simply no assignment."""
    cfg = parse_pack_txt_text("exported\n\n16\nfont*\n")
    assert cfg.bucket_for('coin_00') is None
    assert cfg.assign('coin_00') is None
    groups, unmatched = cfg.group_sprites(['font_a', 'coin_00'])
    assert groups == {0: ['font_a']}
    assert unmatched == ['coin_00']


def test_generated_pack_pal_txt_grammar():
    """A bare number *inside* a block is a sprite name, not a new block."""
    cfg = parse_pack_txt_text(CORPUS_PACK_PAL_TXT)
    assert len(cfg.buckets) == 3
    font = cfg.buckets[1]
    assert (font.max_colors, font.patterns) == (4, ('font*',))
    assert font.base_flags == int(SpriteFlag.FULLSIZE)
    third = cfg.buckets[2]
    assert third.max_colors == 32
    assert third.patterns == ('0', 'dot', 'carr*', 'rabb*', 'eyes_*')
    # "0" and "dot" carry no wildcard: they match exactly
    assert cfg.bucket_for('0') is third
    assert cfg.bucket_for('dot') is third
    assert cfg.bucket_for('dot2') is cfg.buckets[0]


def test_bom_and_crlf_are_tolerated(tmp_path):
    p = tmp_path / '!pack.txt'
    p.write_bytes(b'\xef\xbb\xbfexported\r\n\r\n16\r\nfont*\r\n')
    cfg = parse_pack_txt(p)
    assert cfg.exported_dir == 'exported'
    assert cfg.buckets[0].patterns == ('font*',)
    assert cfg.path == p


def test_find_pack_txt(tmp_path):
    assert find_pack_txt(tmp_path) is None
    (tmp_path / '!pack.txt').write_text("exported\n\n16\n*\n")
    assert find_pack_txt(tmp_path) == tmp_path / '!pack.txt'


@pytest.mark.parametrize("text,fragment", [
    ("", "empty config"),
    ("256\n\n*\n", "expected the exported-folder name"),
    ("exported\n\n16\n*\n\nfont*\n16\n", "expected a palette size"),
    ("exported\n\n16\n", "has no filename mask"),
    ("exported\n\n0\n*\n", "palette size must be >= 1"),
    ("exported\n\n16\n<ALPHA> junk\n*\n", "malformed tag line"),
])
def test_malformed_configs_are_rejected(text, fragment):
    with pytest.raises(PackTxtError) as exc:
        parse_pack_txt_text(text)
    assert fragment in str(exc.value)


# ─────────────────────────────────────────────────────────────────────────────
# Tags -> flag bits (measured against utils.exe)
# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("tag,bits", [
    ('<FULLSIZE>', 0x02),
    ('<ADD>',      0x04),
    ('<BG>',       0x08),
    ('<BUMP>',     0x10),
    ('<DUDV>',     0x20),
    ('<REFL>',     0x40),
])
def test_tag_flag_bits(tag, bits):
    cfg = parse_pack_txt_text(f"exported\n\n16\n{tag}\nprobe*\n")
    assert cfg.buckets[0].base_flags == bits
    assert cfg.buckets[0].alpha_override is None


def test_tags_may_share_a_line_and_combine():
    cfg = parse_pack_txt_text("exported\n\n16\n<ADD><BG>\nprobe*\n")
    assert cfg.buckets[0].base_flags == 0x0C


def test_alpha_and_opaque_are_overrides_not_bits():
    on = parse_pack_txt_text("exported\n\n16\n<ALPHA>\np*\n").buckets[0]
    off = parse_pack_txt_text("exported\n\n16\n<OPAQUE>\np*\n").buckets[0]
    assert on.base_flags == 0 and on.alpha_override is True
    assert off.base_flags == 0 and off.alpha_override is False
    # <OPAQUE> wins if both are present - it is the "never mind the pixels" tag
    both = parse_pack_txt_text("exported\n\n16\n<ALPHA><OPAQUE>\np*\n").buckets[0]
    assert both.alpha_override is False


def test_unknown_tags_are_reported_not_silently_dropped():
    b = parse_pack_txt_text("exported\n\n16\n<NOPE>\np*\n").buckets[0]
    assert b.unknown_tags == ('<NOPE>',)
    assert b.base_flags == 0


# ─────────────────────────────────────────────────────────────────────────────
# ALPHA auto-detection
# ─────────────────────────────────────────────────────────────────────────────

def test_alpha_thresholds_match_the_measured_utils_exe_constants():
    assert PACK_TXT_TRANSPARENT_MAX_ALPHA == 8
    assert PACK_TXT_OPAQUE_MIN_ALPHA == 230
    assert PACK_TXT_ALPHA_ENABLE_RATIO == 0.15


def test_alpha_enable_ratio_is_strictly_greater_than():
    """utils.exe: 1500/10000 stays opaque, 1501/10000 enables alpha."""
    assert group_alpha_enabled(1500, 10000) is False
    assert group_alpha_enabled(1501, 10000) is True
    assert group_alpha_enabled(0, 0) is False


def _png(tmp_path, name, alphas):
    """A 1xN RGBA PNG with the given alpha values."""
    a = np.asarray(alphas, dtype=np.uint8)
    rgb = np.full((len(a), 3), 200, dtype=np.uint8)
    img = np.concatenate([rgb, a[:, None]], axis=1).reshape(1, len(a), 4)
    path = tmp_path / f'{name}.png'
    Image.fromarray(img, 'RGBA').save(path)
    return path


def test_sprite_alpha_counts_uses_the_measured_cutoffs(tmp_path):
    """alpha<=8 is invisible, alpha>=230 is opaque, the rest is anti-aliasing."""
    p = _png(tmp_path, 's', [0, 8, 9, 128, 229, 230, 255])
    assert sprite_alpha_counts(p) == (3, 5)      # 9,128,229 semi of 5 visible


def test_group_alpha_is_pooled_over_the_whole_bucket(tmp_path):
    """One clean frame in a bucket does not lose the group its ALPHA flag —
    utils.exe pools the counters per palette, not per sprite (transit_w_new_*
    in the corpus: 17 anti-aliased frames + 1 hard-edged, all flagged)."""
    cfg = parse_pack_txt_text("exported\n\n16\nsoft_*\n")
    _png(tmp_path, 'soft_00', [128] * 50 + [255] * 50)      # 50 % semi
    _png(tmp_path, 'soft_01', [255] * 100)                  # 0 % semi
    flags = resolve_sprite_flags(cfg, tmp_path, ['soft_00', 'soft_01'])
    assert flags == {'soft_00': int(SpriteFlag.ALPHA),
                     'soft_01': int(SpriteFlag.ALPHA)}


def test_group_below_the_ratio_gets_no_alpha(tmp_path):
    cfg = parse_pack_txt_text("exported\n\n16\nhard_*\n")
    _png(tmp_path, 'hard_00', [128] * 15 + [255] * 85)      # exactly 15 %
    assert resolve_sprite_flags(cfg, tmp_path, ['hard_00']) == {'hard_00': 0}
    _png(tmp_path, 'hard_01', [128] * 16 + [255] * 84)      # 16 %
    assert resolve_sprite_flags(cfg, tmp_path, ['hard_01']) == \
        {'hard_01': int(SpriteFlag.ALPHA)}


def test_alpha_tag_beats_the_auto_ratio_on_a_barely_soft_bucket(tmp_path):
    """The corpus's selectcube_* blocks: only 3.7 % anti-aliased pixels, so
    auto-detection would say no — <ALPHA> drops the threshold to zero and any
    anti-aliasing at all is then enough."""
    cfg = parse_pack_txt_text("exported\n\n256\n<ALPHA><FULLSIZE>\nsel_*\n")
    _png(tmp_path, 'sel_00', [128] * 3 + [255] * 97)
    assert resolve_sprite_flags(cfg, tmp_path, ['sel_00']) == \
        {'sel_00': int(SpriteFlag.ALPHA | SpriteFlag.FULLSIZE)}


def test_alpha_tag_does_not_force_a_bucket_with_no_anti_aliasing(tmp_path):
    """`<ALPHA>` is a lowered threshold, not an override — and the threshold
    is still a STRICT bound, so a block whose alpha channel is purely binary
    packs OPAQUE despite the tag.

    Measured on OCT_ladybug, whose art/!pack_pal.txt tags `eat_*`, `hit_*` and
    `reboun*` `<FULLSIZE><ALPHA>`: all three pool 0 semi-transparent pixels
    (0/29910, 0/23834, 0/4266), utils.exe's own bucket listing prints them
    "FULLSIZE" with no ALPHA, and all 14 of their sprites carry Flags 0x02 in
    the shipped container. utils.exe prints no decision line for them at all.
    """
    cfg = parse_pack_txt_text("exported\n\n128\n<ALPHA><FULLSIZE>\neat_*\n")
    _png(tmp_path, 'eat_00', [0] * 20 + [255] * 80)     # keyed, never blended
    assert resolve_sprite_flags(cfg, tmp_path, ['eat_00']) == \
        {'eat_00': int(SpriteFlag.FULLSIZE)}
    # one anti-aliased pixel anywhere in the pool is enough to flip it
    _png(tmp_path, 'eat_01', [128] + [255] * 99)
    assert resolve_sprite_flags(cfg, tmp_path, ['eat_00', 'eat_01']) == \
        {'eat_00': int(SpriteFlag.ALPHA | SpriteFlag.FULLSIZE),
         'eat_01': int(SpriteFlag.ALPHA | SpriteFlag.FULLSIZE)}


def test_alpha_tag_lowers_the_threshold_to_a_strict_zero():
    assert group_alpha_enabled(0, 10000, PACK_TXT_ALPHA_TAGGED_RATIO) is False
    assert group_alpha_enabled(1, 10000, PACK_TXT_ALPHA_TAGGED_RATIO) is True
    assert group_alpha_enabled(0, 0, PACK_TXT_ALPHA_TAGGED_RATIO) is False


def test_alpha_ratio_reflects_the_tag():
    auto = parse_pack_txt_text("exported\n\n16\np*\n").buckets[0]
    on = parse_pack_txt_text("exported\n\n16\n<ALPHA>\np*\n").buckets[0]
    off = parse_pack_txt_text("exported\n\n16\n<OPAQUE>\np*\n").buckets[0]
    assert auto.alpha_ratio == PACK_TXT_ALPHA_ENABLE_RATIO
    assert on.alpha_ratio == PACK_TXT_ALPHA_TAGGED_RATIO == 0.0
    assert off.alpha_ratio is None       # never, whatever the pixels say


def test_opaque_tag_overrides_a_soft_bucket(tmp_path):
    cfg = parse_pack_txt_text("exported\n\n16\n<OPAQUE>\nsoft_*\n")
    _png(tmp_path, 'soft_00', [128] * 90 + [255] * 10)
    assert resolve_sprite_flags(cfg, tmp_path, ['soft_00']) == {'soft_00': 0}
    assert group_alpha_enabled(9000, 10000, None) is False


def test_fullsize_flag_reaches_the_packed_header(tmp_path):
    """The whole point of Task 2 for Task 1: the tag must be in `flags` before
    build_header runs, because FULLSIZE also halves the pivot scale."""
    import struct

    from config import HDR_OFF_FLAGS, HDR_OFF_PIVOT_X, HDR_OFF_PIVOT_Y
    from pack_codec import EncoderPalette, pack_sprite

    cfg = parse_pack_txt_text("exported\n\n64\n<FULLSIZE>\nahover*\n")
    png = _png(tmp_path, 'ahover_00', [255] * 100)
    flags = resolve_sprite_flags(cfg, tmp_path, ['ahover_00'])['ahover_00']
    assert flags == int(SpriteFlag.FULLSIZE)

    pal = EncoderPalette([(0, 0, 0, 0), (200, 200, 200, 255)])
    blob = pack_sprite(str(png), pal, flags=flags,
                       layer_x=8, layer_y=0, pivot_rect=(80, 80, 2, 2))
    assert blob[HDR_OFF_FLAGS] == int(SpriteFlag.FULLSIZE)
    # golden ahover_00 pivot from OCT_get_started/art/packed/ahover_00.raw
    assert struct.unpack_from('<ff', blob, HDR_OFF_PIVOT_X) == (72.5, 80.5)
    assert HDR_OFF_PIVOT_Y == HDR_OFF_PIVOT_X + 4


# ─────────────────────────────────────────────────────────────────────────────
# Palette construction and pack.py wiring
# ─────────────────────────────────────────────────────────────────────────────

def test_build_config_palettes_sizes_every_group_as_declared(tmp_path):
    from pack_codec import build_config_palettes, symbol_bitness_for_size

    cfg = parse_pack_txt_text(
        "exported\n\n256\n*\n\n4\nfont*\n\n129\nt_halftwist*\n")
    files = []
    for name in ('bg_00', 'font_a', 't_halftwist'):
        rng = np.random.default_rng(abs(hash(name)) % 2**32)
        arr = rng.integers(0, 256, size=(8, 8, 4), dtype=np.uint8)
        arr[:, :, 3] = 255
        p = tmp_path / f'{name}.png'
        Image.fromarray(arr, 'RGBA').save(p)
        files.append(str(p))

    assignments, palette_data, unmatched = build_config_palettes(files, cfg)
    assert unmatched == []
    assert [len(c) for c, _ in palette_data] == [256, 4, 129]
    assert [s for _, s in palette_data] == [8, 2, 8]
    assert symbol_bitness_for_size(129) == 8
    assert assignments['bg_00'][0] == 0
    assert assignments['font_a'][0] == 1
    assert assignments['t_halftwist'][0] == 2
    # index 0 of every palette stays the transparent slot
    for colors, _sym in palette_data:
        assert colors[0] == (0, 0, 0, 0)


def test_fresh_header_honours_the_group_symbol_bitness(tmp_path):
    """A 16-colour group must encode at 4 bits, not the 8-bit default.

    Before this, ``symbol_bitness_override`` only took effect on the
    header-reuse path, so every freshly packed sprite was written at 8 bits
    whatever its palette size — the corpus came out 26 % *larger* than
    utils.exe's pack instead of 7 % smaller.
    """
    import struct

    from config import HDR_OFF_COMPRESSION
    from pack_codec import EncoderPalette, pack_sprite

    png = _png(tmp_path, 's', [255] * 64)
    pal = EncoderPalette([(0, 0, 0, 0)] + [(i * 16, 0, 0, 255) for i in range(15)])

    wide = pack_sprite(str(png), pal)
    narrow = pack_sprite(str(png), pal, symbol_bitness_override=4)
    assert struct.unpack_from('<I', wide, HDR_OFF_COMPRESSION)[0] & 0xFF == 8
    assert struct.unpack_from('<I', narrow, HDR_OFF_COMPRESSION)[0] & 0xFF == 4
    assert len(narrow) < len(wide)


def test_reserved_placeholder_gets_a_real_palette_group(tmp_path):
    """utils.exe logs ``0  pal:0 (*)`` — the reserved 0.png is a member of the
    catch-all block, so its palette group must exist in the container (46
    groups / 500 index.bin records for the corpus, not 45 / 499)."""
    from pack_codec import build_config_palettes

    cfg = parse_pack_txt_text("exported\n\n256\n*\n\n4\nfont*\n")
    files = [str(_png(tmp_path, '0', [255] * 4)),
             str(_png(tmp_path, 'font_a', [255] * 4))]
    assignments, palette_data, unmatched = build_config_palettes(files, cfg)
    assert unmatched == []
    assert assignments['0'][0] == 0
    assert assignments['font_a'][0] == 1
    assert len(palette_data) == 2


def _args(**kw):
    import argparse
    base = dict(pack_config=None, no_pack_config=False, manifest=None,
                art_dir='.')
    base.update(kw)
    return argparse.Namespace(**base)


def test_manifest_wins_over_pack_txt(tmp_path, capsys):
    """Manifest-driven apps must be unaffected by a stray !pack.txt."""
    from pack import _resolve_pack_config

    (tmp_path / '!pack.txt').write_text("exported\n\n16\n*\n")
    assert _resolve_pack_config(
        _args(art_dir=str(tmp_path), manifest='plans/x_assets.json')) is None
    assert 'takes precedence' in capsys.readouterr().out


def test_pack_txt_is_auto_detected_without_a_manifest(tmp_path):
    from pack import _resolve_pack_config

    (tmp_path / '!pack.txt').write_text("exported\n\n16\n*\n")
    cfg = _resolve_pack_config(_args(art_dir=str(tmp_path)))
    assert cfg is not None and len(cfg.buckets) == 1


def test_no_pack_config_opts_out(tmp_path):
    from pack import _resolve_pack_config

    (tmp_path / '!pack.txt').write_text("exported\n\n16\n*\n")
    assert _resolve_pack_config(
        _args(art_dir=str(tmp_path), no_pack_config=True)) is None


def test_explicit_pack_config_beats_the_manifest_note(tmp_path):
    """An explicit --pack-config is honoured even alongside a manifest."""
    from pack import _resolve_pack_config

    p = tmp_path / 'custom.txt'
    p.write_text("exported\n\n4\nfont*\n")
    cfg = _resolve_pack_config(_args(pack_config=str(p),
                                     manifest='plans/x_assets.json'))
    assert cfg is not None and cfg.buckets[0].max_colors == 4


def test_missing_pack_config_is_a_hard_error(tmp_path):
    from pack import _resolve_pack_config

    with pytest.raises(SystemExit):
        _resolve_pack_config(_args(pack_config=str(tmp_path / 'nope.txt')))


def test_no_pack_txt_no_config(tmp_path):
    from pack import _resolve_pack_config

    assert _resolve_pack_config(_args(art_dir=str(tmp_path))) is None


def test_malformed_auto_detected_pack_txt_is_a_clean_error(tmp_path, capsys):
    """A bad block boundary in an auto-detected !pack.txt must exit cleanly
    (print + sys.exit(1)) instead of propagating a raw PackTxtError
    traceback, matching the --pack-config-not-found error path above."""
    from pack import _resolve_pack_config

    (tmp_path / '!pack.txt').write_text("exported\n\n16\n*\n\nfont*\n16\n")
    with pytest.raises(SystemExit):
        _resolve_pack_config(_args(art_dir=str(tmp_path)))
    assert "expected a palette size" in capsys.readouterr().out


def test_malformed_explicit_pack_config_is_a_clean_error(tmp_path, capsys):
    """Same clean-exit behaviour when the malformed file is passed
    explicitly via --pack-config rather than auto-detected."""
    from pack import _resolve_pack_config

    p = tmp_path / 'custom.txt'
    p.write_text("exported\n\n16\n*\n\nfont*\n16\n")
    with pytest.raises(SystemExit):
        _resolve_pack_config(_args(pack_config=str(p)))
    assert "expected a palette size" in capsys.readouterr().out
