@echo off
set exp=exported
set app=app_ai_template

del /Q "%app%_ids.h"
del /Q ".\packed\*.png" 
del /Q ".\%exp%\*.png"
del /Q ".\%exp%\*.psl"
del /Q ".\%exp%\*.log"
del /Q ".\*.log"
              
mkdir ".\%exp%"
mkdir ".\packed"
xcopy "0.png" ".\%exp%" /Y

echo ===== Exporting... =====
 "..\..\psd\bin\psd.exe" "assets.psd" "%exp%" "" "-log"
  "..\..\psd\bin\psd.exe" "font_1.fnt" "%exp%" "" "-font-log"
 "..\..\psd\bin\psd.exe" "font_2.fnt" "%exp%" "" "-font-log"
 "..\..\psd\bin\psd.exe" "font_3.fnt" "%exp%" "" "-font-log"

echo ===== Linking... =====
"..\..\utils\bin\utils.exe" "!pack.txt" "packed" "%app%_ids.h" "-hq-log"

::Copy autogenerated header with ids 
xcopy "%app%_ids.h" "..\..\sim\src\" /Y

::Copy app header from template but only if it's not exists yet
echo FN|xcopy "..\..\sim\src\app_ai_template.h" "..\..\sim\src\%app%.h" /Q /-Y >nul

echo ===== Done! =====
