#pragma once
#include "oct_api.h"
#include "oct_consts.h"

// Include resource IDs generated by the packer tool
#include "app_game_template_ids.h"

#define APP_PNG "..\\..\\app_tower_defence\\art\\packed"
#define APP_SND "..\\..\\app_tower_defence\\art\\mp3"

#define OBJECTS_CAP 400     // Scene capacity - maximum objects count possible
#define GAP         18      // Width of physical border between wowcube's displays in pixels

// ==========================================================================================
//                                  GLOBAL CONSTANTS AND TYPES
// ==========================================================================================

// Game State Enumeration (State Machine)
enum GAME_STATE
{
    STATE_MAIN_MENU, // Main Menu
    STATE_COUNTDOWN, // Countdown (universal transition)
    STATE_GAME_PHASE_1, // First gameplay phase
    STATE_GAME_PHASE_2, // Second gameplay phase
    STATE_WIN, // Victory
    STATE_LOOSE // Defeat
};

// Extended scene object structure
struct appObject_t : octSprite_t
{
    int Health; // Example: object health
    float Vx, Vy; // Velocity
    // Add other game-specific fields here
};

// Global game variables
struct appVars_t
{
    int AppTick; // Total application tick counter

    GAME_STATE CurrentState; // Current state
    GAME_STATE NextState; // State to transition to after COUNTDOWN

    int CountdownTimer; // Timer for the current state (e.g., for countdown)
    int LevelIndex; // Current level
    int Score; // Current score
};

// [NOTE]: All global variables should be defined with the TL macro
TL appObject_t Objects[OBJECTS_CAP];
TL appVars_t Vars;

// ==========================================================================================
//                                  HELPER FUNCTIONS
// ==========================================================================================

// Clear all objects (except system ones if needed)
void ClearScene()
{
    // Restart object array. This is a "soft" reset, objects are removed.
    OCT_restart((int*)Objects, OBJECTS_CAP, sizeof(appObject_t));
}

// Set new state
void SetState(GAME_STATE newState)
{
    Vars.CurrentState = newState;
    Vars.CountdownTimer = 0;
}

// Start countdown with transition to targetState
void StartCountdown(int seconds, GAME_STATE nextState)
{
    Vars.NextState = nextState;
    Vars.CountdownTimer = seconds * 20; // 20 ticks per second
    SetState(STATE_COUNTDOWN);
}

// Draw background on all 24 cube screens
// Uses WoWCube topology logic: 6 faces * 4 quadrants
void DrawBackground(int bmp_id)
{
    // WoWCube has 24 "screens" (quadrants).
    // We iterate through all of them and place the background sprite.
    for (int q = 0; q < 24; ++q)
    {
        // q / 4 = face index (Plane)
        // XSIGN and YSIGN help to correctly orient coordinates (120, 120) within the face
        // 40 - is the layer (Z-order), the lower the value, the deeper the object
        OCT_add(40, false, q / 4, 120.0f * XSIGN[q % 4], 120.0f * YSIGN[q % 4], 0, false, bmp_id, bmp_id, 0);
    }
}

// Level loading (base)
void LoadLevel(int levelIdx)
{
    ClearScene();
    DrawBackground(BMP_BG);

    // Example loading logic
    Vars.LevelIndex = levelIdx;

    // Here you can place game objects depending on levelIdx
    // ...
}

// ==========================================================================================
//                                  STATE LOGIC
// ==========================================================================================

void DrawMainMenu()
{
    // Initialization when entering the menu
    ClearScene();
    DrawBackground(BMP_BG);

    // Add logo or "Tap to Start" text
    // (example conditional, coordinates and layer depend on your graphics)
    OCT_add(10, true, OCT_PLANE_FRONT, 0, 0, 0, false, BMP_TITLE, BMP_TITLE, 0);


    // Menu logic (waiting for tap is handled in on_tap)
}

void UpdateCountdown()
{
    Vars.CountdownTimer--;

    // Example of displaying text for debug or UI
    // char buf[16];
    // sprintf(buf, "%d", (Vars.StateTimer / 50) + 1);
    // OCT_text(buf); 

    if (Vars.CountdownTimer <= 0)
    {
        SetState(Vars.NextState);
    }
}

void StartGamePhase1()
{
    // Phase 1 initialization
    // Maybe load level if we came from menu
    if (Vars.LevelIndex == 0) LoadLevel(1);

    // Phase 1 logic: character movement, collision checks
    // ...

    // Transition condition to second phase (example)
    // if (ConditionMet) SetState(STATE_GAME_PHASE_2);
}

void StartGamePhase2()
{
    // Phase 2 logic
    // ...
}

void DrawWin()
{
    ClearScene();
    // Show win screen
    OCT_add(10, true, OCT_PLANE_FRONT, 0, 0, 0, false, BMP_WIN, BMP_WIN, 0);
}

void DrawLoose()
{
    ClearScene();
    // Show defeat screen
    OCT_add(10, true, OCT_PLANE_FRONT, 0, 0, 0, false, BMP_LOOSE, BMP_LOOSE, 0);
}


// ==========================================================================================
//                                  WASM EXPORTS (ENTRY POINTS)
// ==========================================================================================

WASM_EXPORT void on_init()
{
    // Initialize object memory
    OCT_restart((int*)Objects, OBJECTS_CAP, sizeof(appObject_t));

    // Setup screen layout (standard cube with gaps)
    OCT_viewports_layout(SCHEME_CUBE, GAP, GAP);

    // Developer mode (FPS, clear screen)
    OCT_dev_mode(OCT_DEV_CLEAR_SCREEN /*| OCT_DEV_TEXT | OCT_DEV_FPS*/);

    Vars.AppTick = 0;
    Vars.Score = 0;
    Vars.LevelIndex = 0;

    // Start with the main menu
    SetState(STATE_MAIN_MENU);
}


WASM_EXPORT void on_pretwisted(int32_t twid)
{
    // Called before face rotation starts
    twid;
}


WASM_EXPORT void on_twisted(int32_t twid, uint32_t disconnected_ms)
{
    // Ignore half-twists if needed
    if (twid >= OCT_TWIST_HALF) return;

    // Here you can implement game field changes on rotation
    // For example, if it's a puzzle, recalculate connections between objects

    // Example from app_2048:
    // for (int i = 0; i < 4; ++i)
    //    ProcessQuad(OCT_TWISTS[twid].QuadsRing1[i], OCT_TWISTS[twid].QuadsRing2[i]);

    switch (Vars.CurrentState)
    {
    case STATE_MAIN_MENU:
        // DrawMainMenu();
        break;
    case STATE_COUNTDOWN:
        // UpdateCountdown();
        break;
    case STATE_GAME_PHASE_1:
        // StartGamePhase1();
        break;
    case STATE_GAME_PHASE_2:
        // StartGamePhase2();
        break;
    case STATE_WIN:
        // DrawWin();
        break;
    case STATE_LOOSE:
        // DrawLoose();
        break;
    }

    twid;
    disconnected_ms;
}


WASM_EXPORT void on_tap(int32_t tapid)
{
    OCT_trace(0, "tapid = %d\n", tapid);
}


WASM_EXPORT void on_tick()
{
    // Count total tick
    Vars.AppTick++;

    // Main State Machine loop
    switch (Vars.CurrentState)
    {
    case STATE_MAIN_MENU:
        break;
    case STATE_COUNTDOWN:
        UpdateCountdown();
        break;
    case STATE_GAME_PHASE_1:
        break;
    case STATE_GAME_PHASE_2:
        break;
    case STATE_WIN:
        break;
    case STATE_LOOSE:
        break;
    }
}
